#!/usr/bin/env python3
# Convert an image into the LVGL TRUE_COLOR_ALPHA (RGB565 LE + A8) C-array
# used as the ARIA boot logo (ui_img_logo_png). Matches the existing 400x400
# descriptor so no other code needs to change.
import sys
from PIL import Image

SRC = sys.argv[1]
DST = sys.argv[2]
W = H = 400

img = Image.open(SRC).convert("RGBA")

# Scale to fit within WxH preserving aspect (the logo is wide; this letterboxes
# it vertically on black, which is invisible on the black startup screen).
scale = min(W / img.width, H / img.height)
new_w = max(1, round(img.width * scale))
new_h = max(1, round(img.height * scale))
img = img.resize((new_w, new_h), Image.LANCZOS)

canvas = Image.new("RGBA", (W, H), (0, 0, 0, 255))
canvas.paste(img, ((W - new_w) // 2, (H - new_h) // 2), img)

px = canvas.load()
out = bytearray()
for y in range(H):
    for x in range(W):
        r, g, b, a = px[x, y]
        c565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out.append(c565 & 0xFF)         # low byte (little-endian)
        out.append((c565 >> 8) & 0xFF)  # high byte
        out.append(a)                   # alpha

lines = []
for i in range(0, len(out), 32):
    lines.append("    " + ",".join("0x%02x" % v for v in out[i:i + 32]) + ",")
body = "\n".join(lines)

c = f"""// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: assets/logo.png (ARIA)
const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_logo_png_data[] = {{
{body}
}};
const lv_img_dsc_t ui_img_logo_png = {{
    .header.always_zero = 0,
    .header.w = {W},
    .header.h = {H},
    .data_size = sizeof(ui_img_logo_png_data),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = ui_img_logo_png_data
}};
"""

with open(DST, "w") as f:
    f.write(c)

print(f"wrote {DST}: {W}x{H}, {len(out)} bytes ({len(out)//1024} KB)")
